### ISSUE TITLE
Read-only ratings

### ISSUE THREAD

**Issue by peter-mghendi** [timyboy12345/Rating.js#2]
Hi. This is so far the best all round rating library I've come across so far. Seems to have no support for read-only ratings though. I would like to accept as well as display ratings on a webpage, and it seems I am not able to do the latter.

Apart from that, (I don't know whether I should open a new issue for this) support for the data- API would be a nice feature to have.

**Comment by timyboy12345** [comment]
Great ideas!

With the new version, it's possible to use data-attributes, which does confine the possibilities of the `onclick` function, but it's a great help if you want a simple rating field without any custom javascript. It's explained on the readme and the [examples page](https://timyboy12345.github.io/Rating.js/) contains some examples.

I've also added read-only ratings, which can be used through a simple option (also available as a data-attribute).
