### ISSUE TITLE
How to Update The value using Jquery Again 

### ISSUE THREAD

**Issue by ShafeerKhan** [timyboy12345/Rating.js#3]
Hi i want to update the star rating back when its editing and it not setting value  i put i through ajax value .. please provide a change value function also

**Comment by timyboy12345** [comment]
I've added the ability to alter the rating element. This is done by recalling the `.rating()` function on the element. This will remove all existing stars, and recreate the element with the given options. So if you want to use the same options as when you created the element, you will have to give the same options.
